import Head from 'next/head';
import styles from '@/styles/Home.module.css';

export default function Coffee() {
    return (
        <>
            <Head>
                <title>Coffee Roaster App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="https://www.flaticon.com/free-icons/coffee"
                />
            </Head>
            <main className={styles.main}>
                <div className={styles.header}>
                    Coffee Page
                </div>
            </main>
        </>
    );
}

export async function getStaticPaths() {
    return {
        paths: [
            { params: { id: '1' } },
            { params: { id: '2' } },
        ],
        fallback: false, // can also be true or 'blocking'
    };
}

// `getStaticPaths` requires using `getStaticProps`
export async function getStaticProps() {
    return {
        // Passed to the page component as props
        props: { post: {} },
    };
}
