import Head from 'next/head';
import styles from '@/styles/Home.module.css';

type GetStaticPathsParams = {
    params: { id: number };
};

type Coffee = {
    Id: number;
};

type CoffeeParam = {
    coffee: Coffee;
};

export default function Coffee({ coffee }: CoffeeParam) {
    console.log(coffee);

    return (
        <>
            <Head>
                <title>Coffee Roaster App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="https://www.flaticon.com/free-icons/coffee"
                />
            </Head>
            <main className={styles.main}>
                <div className={styles.header}>Coffee {coffee.Id} Page</div>
            </main>
        </>
    );
}

export async function getStaticPaths() {
    const coffees = await fetch(`http://127.0.0.1:3000/api/coffees`).then(
        (data) => {
            return data.json();
        },
    );

    const paths = await coffees.map((coffee: { Id: number }) => ({
        params: { id: coffee.Id },
    }));

    return { paths, fallback: false };
}

// `getStaticPaths` requires using `getStaticProps`
export async function getStaticProps(context: GetStaticPathsParams) {
    const { id } = context.params;

    const coffee = await fetch(`http://127.0.0.1:3000/api/coffees/${id}`).then(
        (data) => {
            return data.json();
        },
    );

    return {
        // Passed to the page component as props
        props: { coffee },
    };
}
