import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { Coffee } from '../../models/Coffee/CoffeeModel';
import Link from 'next/link';

type GetStaticPathsParams = {
    params: { id: number };
};

type CoffeeParams = {
    coffee: Coffee;
};

export default function CoffeePage({ coffee }: CoffeeParams) {
    console.log(coffee);

    return (
        <>
            <Head>
                <title>Coffee Roaster App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="https://www.flaticon.com/free-icons/coffee"
                />
            </Head>
            <main className={styles.main}>
                <div className={styles.grid}>
                    <Link
                        className={styles.card}
                        href={`/coffees/${+coffee.Id + 1}`}
                    >
                        <button className={styles.header}>+</button>
                    </Link>
                    <div className={styles.header}>
                        Coffee {coffee.Owner[1]} Page
                    </div>
                    <Link
                        className={styles.card}
                        href={`/coffees/${+coffee.Id - 1}`}
                    >
                        <button className={styles.header}>-</button>
                    </Link>
                </div>
            </main>
        </>
    );
}

export async function getStaticPaths() {
    const coffees = await fetch(`http://127.0.0.1:3000/api/coffees`).then(
        (data) => {
            return data.json();
        },
    );

    const paths = await coffees.map((coffee: { Id: number }) => ({
        params: { id: coffee.Id },
    }));

    return { paths, fallback: false };
}

// `getStaticPaths` requires using `getStaticProps`
export async function getStaticProps(context: GetStaticPathsParams) {
    const { id } = context.params;

    const coffee = await fetch(`http://127.0.0.1:3000/api/coffees/${id}`).then(
        (data) => {
            return data.json();
        },
    );

    return {
        // Passed to the page component as props
        props: { coffee },
    };
}
