import Head from 'next/head';
import styles from '@/styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Coffee Roaster App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          <a className={styles.card}>Coffee Roaster App</a>
          <a className={styles.card}>Coffees</a>
          <a className={styles.card}>Favourites</a>
          <a className={styles.card}>Profile</a>
          <a className={styles.card}>Log in</a>
        </div>
      </main>
    </>
  );
}
