import Head from 'next/head';
import Link from 'next/link';
import styles from '@/styles/Home.module.css';

export default function Home() {
    return (
        <>
            <Head>
                <title>Coffee Roaster App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="https://www.flaticon.com/free-icons/coffee"
                />
            </Head>
            <main className={styles.main}>
                <div className={styles.grid}>
                    <a className={styles.card}>Coffee Roaster App</a>
                    <Link className={styles.card} href="/coffees">
                        Coffees
                    </Link>
                    <Link className={styles.card} href="/map">
                        Map
                    </Link>
                    <Link className={styles.card} href="/profile">
                        Profile
                    </Link>
                    <Link className={styles.card} href="/login">
                        Log in
                    </Link>
                </div>
            </main>
        </>
    );
}
