import Head from 'next/head';
import Link from 'next/link';
import styles from '@/styles/Home.module.css';
import MapComponent from '@/ components/MapComponent';
import NavBar from '@/ components/NavBarComponent';

export default function Home() {
    return (
        <>
            <Head>
                <title>Coffee Roaster App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="https://www.flaticon.com/free-icons/coffee"
                />
            </Head>
            <NavBar />
            <MapComponent />
        </>
    );
}
